### ISSUE TITLE
Testes do loading-provider com warnings

### ISSUE THREAD

**Issue by adriano-lemos-dev** [tst-labs/basilar#18]
@rcvieira favor corrigir o warning inserido nos testes do componente `loading-provider`.

``` shell
  ● Console

    console.error
      Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnOnFunctionType (node_modules/react-dom/cjs/react-dom.development.js:14900:5)
      at reconcileChildFibers (node_modules/react-dom/cjs/react-dom.development.js:15837:9)
      at reconcileChildren (node_modules/react-dom/cjs/react-dom.development.js:19174:28)
      at updateHostRoot (node_modules/react-dom/cjs/react-dom.development.js:19883:5)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21615:14)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27426:14)

```

**Comment by rcvieira** [comment]
Commitei direto na main sem querer. Mas excluí o warning.
